title: "analytics-service"
description: "A site for the Analytic Service team of NHS Digital/ Data Services to share and discuss its open-source technology and publications work with the world."
future: true
timezone: Europe/London
theme: jekyll-theme-slate
